spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/multi-board
    jdbc-url: jdbc:mysql://127.0.0.1:3306/multi-board
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#spring.datasource.jdbcUrl=${spring.datasource.board.url}
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/multi-board
#spring.datasource.jdbc-url=jdbc:mysql://127.0.0.1:3306/multi-board
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
